GET http://localhost:3001/api/links/links-data
### 

// Registerw
POST http://localhost:3001/api/links/upload
content-type: application/json

{ 
  "name": "REST 1",
  "link": "google.lv/google",
  "color1": "#00FF00",
  "color2": "#FF00FF",
  "username": "rest-test"
}
###

// List of all links an all files ids and metadata
GET http://localhost:3001/api/links/get-links-and-pdfs-ids
###

// List of all links ONLY
GET http://localhost:3001/api/links/get-link-data
###

// Select one
GET http://localhost:3001/api/pdfs/627684ef1612b7274d949272
###

// Delete one 
DELETE http://localhost:3001/api/links/627ea2a0fc626afe341333a2
###


// BOT TESTING
GET http://localhost:3001/api/bot/links-data
###

POST http://localhost:3001/api/bot/sync-sharepoint
content-type: application/json

{
  "fileNames": ["file1.txt", "file2.txt", "file3.txt", "file4.txt"]
}
###