GET http://localhost:3001/
### 

// Registerw
POST http://localhost:3001/catalogues/add
content-type: application/json

{ 
  "name": "Katalogs 1",
  "link": "links 1"
}
###

// List of all links
GET http://localhost:3001/api/links/get-links-and-pdfs-ids
###

// Select one
GET http://localhost:3001/api/pdfs/627684ef1612b7274d949272
###

// Delete one 
DELETE http://localhost:3001/api/links/627ea2a0fc626afe341333a2
###




// List of all FILES
GET http://localhost:3001/api/pdfs/get-files-ids
###

// Select one file JSON object
GET http://localhost:3001/files/477893fe50a8aca4116b5abc9b785a94.png
###

// Select one file
GET http://localhost:3001/readpdf/477893fe50a8aca4116b5abc9b785a94.png
###