domain = "https://qrkodi.herokuapp.com/"
login = domain + "/auth/login"
logout = domain + "/logout"
postNewLink = domain + "/api/bot/upload"
allLinksData = domain + "/api/bot/links-data"
deleteOne = domain + "/api/bot/delete/"
syncSharepoint = domain + "api/bot/sync-sharepoint"